/* ===== Drills ===== */
const DRILLS=[
{id:'gk-react',cat:'Individual',pos:['gk'],name:'Set position & reaction saves',focus:'Shot-stopping, footwork, recovery',players:'1 GK + 1 server',area:'Goal + 12 m',time:'15 min',int:'High',kit:'Balls ×10, 2 cones',
 setup:'Keeper on the goal line between two cones 2 m inside each post. Server 12 m out with a supply of balls.',
 steps:['Keeper starts in the set position: feet shoulder-width, knees soft, hands ready at hip height','Server strikes low to one side; keeper takes a quick step and dives to catch','Keeper recovers to his feet and back to centre, setting before the next strike','Next strike goes to the other side or at head height','Work 30 s, rest 60 s. 6 reps per set'],
 pts:['Be set, not moving, when the ball is struck','Lead with the hands, not the shoulder','Dive forward at an angle, not sideways along the line','Recover to the feet in one movement'],
 prog:['Server uses a mannequin as a screen','Second server strikes from a different angle','Add a rebound: server follows up on spills'],
 tm:{work:30,rest:60,rounds:6,sets:2,sr:120},
 sc:{view:'def',e:{h:[50,97,'GK'],k:[50,84,'S','k'],c1:[45,99,'','c'],c2:[55,99,'','c']},b:'k',f:[
  {h:'Set',c:'Keeper in the set position on the line, between the two cones.'},
  {h:'Strike',c:'Low strike to the right. Keeper steps and dives forward to catch.',b:'h',m:{h:[57,98]},d:900},
  {h:'Recover',c:'Back to the feet, back to centre, set again.',b:'k',m:{h:[50,97]}},
  {h:'Strike',c:'Next strike to the left side.',b:'h',m:{h:[43,98]},d:900}]}},

{id:'gk-cross',cat:'Individual',pos:['gk'],name:'Crosses & claiming',focus:'Command of the box, catching at height',players:'1 GK + 2 servers + 1–2 passive attackers',area:'Penalty area',time:'15 min',int:'Medium',kit:'Balls ×12, 4 cones',
 setup:'Servers on each wing level with the edge of the box. One or two passive attackers in the six-yard box.',
 steps:['Keeper starts in his crossing position: back half of the goal, open body','Server on the right crosses; keeper calls “Keeper!” and attacks the ball','Catch at the highest point, knee up, and land balanced','Keeper rolls the ball out and resets; next cross from the left','Alternate sides; 8 crosses per set'],
 pts:['Call early and loud','Take off on one leg, drive the opposite knee up','Catch with hands slightly in front of the head','If you can’t catch, punch high and wide'],
 prog:['Attackers become active','Add in-swinging and out-swinging deliveries','Keeper must distribute after each catch to a target'],
 tm:{work:20,rest:40,rounds:8,sets:2,sr:120},
 sc:{view:'def',e:{h:[50,98,'GK'],k1:[88,82,'S','k'],k2:[12,82,'S','k'],x:[48,92,'A','o'],c1:[86,84,'','c'],c2:[14,84,'','c']},b:'k1',f:[
  {h:'Position',c:'Ball is wide right. Keeper shifts to the back half of the goal.',m:{h:[54,97]}},
  {h:'Claim',c:'Cross is lifted in. Keeper calls and attacks it at its highest point.',b:'h',m:{h:[50,93]},d:1500},
  {h:'Reset',c:'Roll the ball out, get back on the line.',b:'k2',m:{h:[46,97]}},
  {h:'Claim',c:'Cross from the left. Same again: call, attack, catch.',b:'h',m:{h:[50,93]},d:1500}]}},

{id:'cb-aerial',cat:'Individual',pos:['cb'],name:'Aerial duels & clearances',focus:'Heading, timing, body contact',players:'2 defenders + 1 attacker + 1 server',area:'30 × 20 m',time:'15 min',int:'High',kit:'Balls ×10, 4 cones, 2 mini goals as targets',
 setup:'Server 30 m away. Defender and passive attacker in the middle. Two mini goals wide as clearance targets.',
 steps:['Server lofts a long ball toward the pair','Defender reads the flight, gets body contact with the attacker first','Attack the ball with a run and jump, heading through the middle of the ball','Aim the clearance high and wide toward a target goal','Swap defenders after each rep'],
 pts:['Judge the flight early and move your feet','Use your arms for balance, not to push','Eyes open, neck strong, head through the ball','Height and distance before accuracy'],
 prog:['Attacker becomes fully active','Ball delivered from wide like a cross','Defender must head to a teammate instead of clearing'],
 tm:{work:15,rest:45,rounds:8,sets:2,sr:120},
 sc:{view:'mid',grid:[[24,40,52,40,'30 × 20 m']],e:{h:[50,66,'CB'],x:[52,62,'A','o'],k:[50,30,'S','k'],g1:[26,74,'','g'],g2:[74,74,'','g']},b:'k',f:[
  {h:'Serve',c:'Server lofts a long ball toward the pair.',b:[51,62],d:1600},
  {h:'Attack',c:'Defender gets body contact first and attacks the ball at its highest point.',m:{h:[50,62],x:[53,60]},b:[50,61]},
  {h:'Clear',c:'Head it high and wide toward a target goal.',b:[24,74],d:1300}]}},

{id:'def-footwork',cat:'Individual',pos:['cb','fb'],name:'Defensive footwork ladder',focus:'Jockeying, hip turn, recovery sprint',players:'1+ defenders',area:'20 × 15 m',time:'12 min',int:'Medium',kit:'6 cones',
 setup:'Zig-zag of cones 5 m apart down a channel. Finish cone 10 m beyond the last one.',
 steps:['Start side-on at the first cone, low and on the balls of your feet','Shuffle backward and sideways to the next cone without crossing your feet','At each cone, drop-step and turn the hips to change direction','After the last cone, open up and sprint 10 m forward','Walk back to the start: that’s your rest'],
 pts:['Stay low, head over your knees','Small, quick steps; never cross your feet','Turn the hips, not just the shoulders','Explode out of the final turn'],
 prog:['Coach points left or right at random','Add an attacker dribbling through the cones','Finish with a 1v1 to a mini goal'],
 tm:{work:12,rest:48,rounds:6,sets:2,sr:90},
 sc:{view:'mid',e:{h:[44,70,'D'],c1:[44,70,'','c'],c2:[58,64,'','c'],c3:[44,58,'','c'],c4:[58,52,'','c'],c5:[44,46,'','c'],c6:[50,36,'','c']},f:[
  {h:'Shuffle',c:'Side-on, shuffle across to the second cone. Do not cross your feet.',m:{h:[58,64]}},
  {h:'Drop-step',c:'Turn the hips and drive to the next cone.',m:{h:[44,58]}},
  {h:'Repeat',c:'Same again. Stay low the whole way.',m:{h:[58,52]}},
  {h:'Turn',c:'Last change of direction.',m:{h:[44,46]}},
  {h:'Sprint',c:'Open up and sprint out to the finish cone.',m:{h:[50,36]},d:900}]}},

{id:'fb-overlap',cat:'Individual',pos:['fb','wb'],name:'Overlap & cross repeats',focus:'Overlaps, crossing at speed, repeat sprints',players:'1 full-back + 1 server/winger + 2 strikers + GK',area:'Half pitch, one flank',time:'15 min',int:'High',kit:'Balls ×12, 4 cones, 1 mannequin',
 setup:'Full-back starts at the halfway line on the flank. Winger 15 m ahead. Mannequin as the opposing full-back. Two strikers on the edge of the box.',
 steps:['Full-back passes into the winger’s feet and sprints the overlap','Winger shifts inside and slides the ball into the full-back’s path','Full-back crosses first time from the channel','Strikers attack the near and far post','Full-back jogs back along the touchline: that is the recovery'],
 pts:['Call “Overlap!” as you run','Look up before the ball arrives','Cross early into the space between defenders and keeper','Hit the target zone, not the keeper'],
 prog:['Add an active defender','Alternate overlap and underlap','Full-back must recover to the halfway line in under 12 seconds'],
 tm:{work:12,rest:48,rounds:8,sets:2,sr:120},
 sc:{view:'att',e:{h:[86,54,'FB'],a:[80,38,'W'],p:[86,26,'','p'],b:[44,24,'9'],c:[58,26,'9'],g:[50,2,'GK','o']},b:'h',f:[
  {h:'Pass',c:'Full-back plays into the winger and sets off on the overlap.',b:'a',m:{h:[92,40]}},
  {h:'Release',c:'Winger shifts inside and returns it into the channel.',b:'h',m:{a:[72,32],h:[93,22]}},
  {h:'Cross',c:'First-time cross. Strikers attack near and far post.',b:'b',m:{b:[46,8],c:[58,10],h:[93,16]}},
  {h:'Finish',c:'Finish, then the full-back jogs back to the start.',b:[48,0],m:{h:[86,54]},d:1800}]}},

{id:'mid-scan',cat:'Individual',pos:['dm','cm'],name:'Scan, receive, turn',focus:'Scanning, body shape, receiving on the half-turn',players:'1 midfielder + 2 servers + 1 coach',area:'20 × 20 m',time:'15 min',int:'Medium',kit:'Balls ×6, 4 cones as two gates',
 setup:'Midfielder in the middle of the square. Server at each end. Two 3 m gates on the left and right sides.',
 steps:['Server plays into the midfielder','As the ball travels, the coach points to a gate','The midfielder scans, opens his body and turns away through that gate','He dribbles out and passes to the far server','He returns to the middle to receive from that server'],
 pts:['Scan twice before the ball arrives','Receive on the back foot, half-turned','Turn away from the imaginary pressure','First touch out of your feet, not under you'],
 prog:['Add a passive then active defender behind the midfielder','Two-touch limit','Coach calls a colour instead of pointing'],
 tm:{work:45,rest:30,rounds:6,sets:2,sr:90},
 sc:{view:'mid',grid:[[30,38,40,24,'20 × 20 m']],e:{h:[50,50,'8'],a:[50,64,'S'],b:[50,36,'S'],k:[50,30,'C','k'],c1:[30,46,'','c'],c2:[30,54,'','c'],c3:[70,46,'','c'],c4:[70,54,'','c']},b:'a',f:[
  {h:'Scan',c:'Server plays in. The midfielder scans over both shoulders as the ball travels.',b:'h'},
  {h:'Turn',c:'The coach points right. Receive half-turned and go through the right gate.',m:{h:[72,50]}},
  {h:'Pass',c:'Pass to the far server.',b:'b'},
  {h:'Reset',c:'Back into the middle for the next ball.',m:{h:[50,50]}}]}},

{id:'att-1v1',cat:'Individual',pos:['w','am'],name:'1v1 attacking channel',focus:'Beating a defender, change of pace',players:'Pairs (attacker v defender)',area:'15 × 25 m channel',time:'15 min',int:'High',kit:'Balls ×6, 4 cones, 1 mini goal',
 setup:'A channel with a mini goal at one end. Defender starts on the goal line and passes to the attacker at the other end.',
 steps:['Defender passes to the attacker and steps out to defend','Attacker drives at the defender at speed','Use a feint or a change of direction to unbalance him','Accelerate past and finish in the mini goal','Swap roles after every rep'],
 pts:['Attack the front foot of the defender','Change speed, not just direction','Keep the ball close as you get near him','Explode for 5 m after beating him'],
 prog:['Add a recovering second defender after 3 s','Must finish within 6 s','Finish with a cut-back to a striker'],
 tm:{work:10,rest:50,rounds:8,sets:2,sr:120},
 sc:{view:'mid',grid:[[38,26,24,44,'15 × 25 m']],e:{h:[50,66,'A'],x:[50,30,'D','o'],g:[50,24,'','g']},b:'x',f:[
  {h:'Serve',c:'Defender passes in and steps out.',b:'h',m:{x:[50,40]}},
  {h:'Drive',c:'Attacker drives at him at speed.',m:{h:[50,50],x:[50,44]}},
  {h:'Feint',c:'Feint one way, shift the ball the other.',m:{h:[44,44],x:[52,43]}},
  {h:'Finish',c:'Accelerate past and finish in the mini goal.',m:{h:[46,32],x:[50,40]},b:[50,24]}]}},

{id:'w-cutin',cat:'Individual',pos:['w'],name:'Cut inside & finish',focus:'Inverted winger finishing',players:'1 winger + 1 server + GK',area:'Final third',time:'15 min',int:'High',kit:'Balls ×10, 1 mannequin, 2 cones',
 setup:'Winger starts wide on the flank. Mannequin as the full-back on the edge of the box.',
 steps:['Server plays into the winger’s feet on the touchline','Winger drives at the mannequin','Cut inside onto the stronger foot','Curl a shot toward the far post','Alternate flanks every 4 reps'],
 pts:['Attack at speed, slow just before the cut','Open the body to see the far post','Strike across the ball with the inside of the foot'],
 prog:['Active defender instead of a mannequin','Option to go outside if the defender overcommits','Add a full-back overlap as a decoy'],
 tm:{work:10,rest:50,rounds:8,sets:2,sr:120},
 sc:{view:'att',e:{h:[88,36,'W'],p:[80,24,'','p'],k:[86,52,'S','k'],g:[50,2,'GK','o']},b:'k',f:[
  {h:'Receive',c:'Server plays into the winger.',b:'h'},
  {h:'Drive',c:'Drive at the mannequin at speed.',m:{h:[84,26]}},
  {h:'Cut',c:'Cut inside onto the stronger foot.',m:{h:[70,20]}},
  {h:'Curl',c:'Curl it toward the far post.',b:[42,0],m:{g:[48,3]},d:1500}]}},

{id:'st-finish',cat:'Individual',pos:['st'],name:'Movement & first-time finish',focus:'Losing a marker, near-post finishing',players:'1–2 strikers + 1 server + GK',area:'Penalty area',time:'15 min',int:'High',kit:'Balls ×12, 2 mannequins',
 setup:'Two mannequins as centre-backs at the penalty spot. Server wide on the edge of the box.',
 steps:['Striker starts between the mannequins','Make a movement away toward the far post','Check and sprint across the front of the near mannequin','Server plays a firm low ball across','Finish first time; reset and alternate sides'],
 pts:['Move away before you move toward','Arrive as the ball arrives','Open your body; use the pace of the ball','Aim low and across the keeper'],
 prog:['Add a live defender','Server varies height: driven, lofted, cut-back','Two strikers make crossing runs'],
 tm:{work:8,rest:52,rounds:10,sets:2,sr:120},
 sc:{view:'att',e:{h:[50,22,'9'],p1:[44,14,'','p'],p2:[56,14,'','p'],k:[82,24,'S','k'],g:[50,2,'GK','o']},b:'k',f:[
  {h:'Move away',c:'Drift toward the far post to lose the imaginary defender.',m:{h:[58,20]}},
  {h:'Attack',c:'Check and sprint across the front of the near mannequin.',m:{h:[50,10]}},
  {h:'Finish',c:'Low ball across, first-time finish.',b:'h',d:1100},
  {h:'Score',c:'Low and across the keeper.',b:[46,0],m:{g:[52,3]}}]}},

{id:'st-holdup',cat:'Individual',pos:['st'],name:'Hold-up & lay-off',focus:'Back-to-goal play, protecting the ball',players:'1 striker + 1 defender + 2 servers',area:'30 × 20 m',time:'12 min',int:'Medium',kit:'Balls ×10, 4 cones',
 setup:'Striker with a defender behind him. Long server 30 m away, support player 10 m to one side.',
 steps:['Long server plays into the striker (feet or chest)','Striker gets his body in first and controls','He lays it off to the support player','He spins off the defender and runs into the box for the return','Rotate roles every 6 reps'],
 pts:['Contact before the ball arrives','Wide base, low centre of gravity','Lay-off to the supporter’s front foot','Spin the moment the ball leaves your foot'],
 prog:['Defender becomes fully active','Add a finish on the return','Two-touch maximum'],
 tm:{work:15,rest:45,rounds:8,sets:2,sr:90},
 sc:{view:'mid',e:{h:[50,34,'9'],x:[50,30,'D','o'],a:[62,46,'8'],k:[50,74,'S','k']},b:'k',f:[
  {h:'Contact',c:'Long ball coming. Striker gets his body into the defender first.',b:'h',d:1600},
  {h:'Lay-off',c:'Control and lay it off to the supporting midfielder.',b:'a'},
  {h:'Spin',c:'Spin off the defender and attack the space behind.',m:{h:[44,20],x:[48,26]}},
  {h:'Return',c:'Return pass into the run.',b:'h'}]}},

{id:'back4',cat:'Unit',pos:['cb','fb'],name:'Back four: shift & squeeze',focus:'Compactness, cover and balance',players:'4 defenders + 4 servers',area:'Half pitch',time:'15 min',int:'Low',kit:'Balls ×6, 8 cones',
 setup:'Back four in their line. Four servers spread across the pitch 25 m in front, passing the ball between them.',
 steps:['Servers pass the ball slowly across their line','Nearest defender steps up to pressure the ball','The others shift across and drop slightly to cover (diagonal line)','When the ball goes backward, the whole line squeezes up together','Coach freezes play to check distances'],
 pts:['10–12 m between defenders, never more','Pressure, cover, balance on every pass','Talk: “Step!”, “Squeeze!”, “Hold!”','The far full-back tucks in'],
 prog:['Servers can play a through ball; defenders must deal with it','Add two attackers making runs','Servers choose when to play long'],
 tm:{work:180,rest:60,rounds:4,sets:1},
 sc:{view:'def',e:{d1:[16,74,'LB'],d2:[38,78,'LCB'],d3:[62,78,'RCB'],d4:[84,74,'RB'],x1:[14,54,'S','o'],x2:[38,50,'S','o'],x3:[62,50,'S','o'],x4:[86,54,'S','o']},b:'x2',f:[
  {h:'Central',c:'Ball central. Flat line, 10–12 m between each defender.'},
  {h:'Wide',c:'Ball goes wide right. Right-back steps, the others shift across and cover.',b:'x4',m:{d4:[84,64],d3:[68,74],d2:[50,76],d1:[30,74]}},
  {h:'Squeeze',c:'Ball played backward: the whole line squeezes up together.',b:'x3',m:{d4:[80,68],d3:[60,68],d2:[42,70],d1:[22,68]}},
  {h:'Wide',c:'Ball switched to the left. Left-back steps; the line shifts across.',b:'x1',m:{d1:[16,62],d2:[32,70],d3:[50,72],d4:[70,70]}}]}},

{id:'build-3v2',cat:'Unit',pos:['gk','cb','dm'],name:'Build-up vs press: 4v2',focus:'Playing out from the back, finding the free player',players:'GK + 2 CBs + 6 v 2 strikers',area:'Penalty area to 35 m',time:'15 min',int:'Medium',kit:'Balls ×10, 4 cones for two gates',
 setup:'Keeper, two centre-backs and a 6 against two pressing strikers. Two gates at 35 m to dribble or pass through.',
 steps:['Keeper starts every rep','Centre-backs split to the edges of the box; the 6 drops in or shows','Strikers press man-to-man','Find the free player and play through a gate','If the strikers win it, they shoot at goal'],
 pts:['Create a 3v2 by dropping the 6','Pass to the far foot of the free player','Drive into space to fix a presser','Keeper stays available for the back-pass'],
 prog:['Add a third presser (4v3)','Limit to two touches','Gates move closer to the centre'],
 tm:{work:90,rest:60,rounds:6,sets:1},
 sc:{view:'def',e:{g:[50,96,'GK'],a:[38,84,'LCB'],b:[62,84,'RCB'],c:[50,74,'6'],x:[44,80,'9','o'],y:[56,80,'9','o'],c1:[20,62,'','c'],c2:[30,62,'','c'],c3:[70,62,'','c'],c4:[80,62,'','c']},b:'g',f:[
  {h:'Start',c:'Keeper has it. Two strikers press the two centre-backs.'},
  {h:'Create 3v2',c:'The 6 drops between the centre-backs, who split wide.',m:{c:[50,84],a:[26,86],b:[74,86],x:[42,82],y:[58,82]}},
  {h:'Free player',c:'Keeper finds the free right centre-back.',b:'b'},
  {h:'Through',c:'He drives through the gate. The press is beaten.',m:{b:[75,62]}}]}},

{id:'rondo',cat:'Unit',pos:['dm','cm','am'],name:'Rondo 4v2',focus:'Passing under pressure, angles, the split pass',players:'6 (4 attackers, 2 defenders)',area:'12 × 12 m',time:'12 min',int:'Medium',kit:'Balls ×6, 4 cones',
 setup:'Four players on the edges of a square, two defenders inside.',
 steps:['Outside players keep the ball with a two-touch limit','Defenders press together to win it or force it out','A pass between the two defenders (split pass) scores a point','A defender who wins it swaps with the player who lost it','Play for 90 seconds, then rest'],
 pts:['Open your body to see two passing options','Move along your line to create an angle','Play to the foot away from pressure','Defenders: one presses, one cuts the split pass'],
 prog:['One-touch only','Make the square smaller','5v2 with a player in the middle'],
 tm:{work:90,rest:45,rounds:6,sets:1},
 sc:{view:'mid',grid:[[38,42,24,16,'12 × 12 m']],e:{a:[38,50,'A'],b:[50,42,'B'],c:[62,50,'C'],d:[50,58,'D'],x:[46,50,'X','o'],y:[54,50,'X','o']},b:'a',f:[
  {h:'Circulate',c:'A plays to B. Defenders shift toward the ball.',b:'b',m:{x:[48,46],y:[54,48]}},
  {h:'Circulate',c:'B to C. One defender presses, one covers.',b:'c',m:{y:[58,49],x:[52,48]}},
  {h:'Circulate',c:'C to D.',b:'d',m:{y:[56,54],x:[50,52]}},
  {h:'Split',c:'Gap opens between the defenders. D plays the split pass to B: point scored.',b:'b'}]}},

{id:'front3-press',cat:'Unit',pos:['st','w','am'],name:'Front three pressing trigger',focus:'Curved runs, pressing traps',players:'3 attackers v 4 defenders + GK',area:'Final third',time:'15 min',int:'High',kit:'Balls ×10, cones for 2 end gates',
 setup:'A back four and keeper build from their goal. Your front three press. Defenders score by passing through the halfway gates.',
 steps:['Keeper plays to a centre-back','Striker curves his run to cut the pass to the other centre-back','The ball goes to the full-back (the trap): the winger presses him from the inside','The striker blocks the back-pass and the far winger tucks in','Win it and finish within 8 seconds'],
 pts:['Press as a unit, not one at a time','Curve the run to use your cover shadow','The pass to the full-back is the trigger','Sprint on the trigger, then slow to stay balanced'],
 prog:['Add their 6 and your 10 (4v5)','Defenders can go long to a target','Count regains per round'],
 tm:{work:120,rest:60,rounds:5,sets:1},
 sc:{view:'att',e:{a:[18,36,'LW'],b:[50,32,'9'],c:[82,36,'RW'],x1:[12,20,'FB','o'],x2:[36,12,'CB','o'],x3:[64,12,'CB','o'],x4:[88,20,'FB','o'],g:[50,2,'GK','o']},b:'x3',f:[
  {h:'Start',c:'Ball is with their right-sided centre-back.'},
  {h:'Curve',c:'Striker curves his run to block the pass across. Wingers stay inside the full-backs.',m:{b:[56,16],a:[22,28],c:[74,26]}},
  {h:'Trigger',c:'He plays to the full-back: the trigger. Right winger presses from the inside.',b:'x4',m:{c:[84,22],b:[66,14],a:[34,22]}},
  {h:'Regain',c:'Ball won high up the pitch. Attack the goal.',b:'c',m:{c:[80,18]}}]}},

{id:'wide-2v1',cat:'Unit',pos:['fb','wb','w'],name:'Wide 2v1 to cross',focus:'Overlaps and underlaps, decision-making',players:'Full-back + winger v 1 defender + 2 strikers + GK',area:'Wide channel + box',time:'15 min',int:'High',kit:'Balls ×10, 4 cones',
 setup:'A wide channel 15 m across. Winger and full-back against one defender. Two strikers waiting in the box.',
 steps:['Winger receives and attacks the defender','Full-back chooses: overlap outside or underlap inside','Winger reads the defender: if he follows the runner, go yourself','Get the cross in from the channel','Strikers attack near and far post'],
 pts:['Communicate the run early','Commit the defender before releasing','Deliver into the danger zone between keeper and defenders'],
 prog:['Defender gets a recovering teammate after 4 s','Two defenders in the box','Only cut-backs count'],
 tm:{work:15,rest:45,rounds:8,sets:2,sr:120},
 sc:{view:'att',e:{a:[88,56,'FB'],b:[86,38,'W'],x:[84,28,'D','o'],c:[46,22,'9'],d:[58,24,'9'],g:[50,2,'GK','o']},b:'b',f:[
  {h:'2v1',c:'Winger attacks the defender; full-back sets off.',m:{b:[84,32],a:[92,40]}},
  {h:'Overlap',c:'The defender sticks with the winger, so the overlap is free.',b:'a',m:{a:[93,22],x:[84,28]}},
  {h:'Cross',c:'Cross in. Strikers split near and far.',b:'c',m:{c:[46,8],d:[60,10]}}]}},

{id:'combo',cat:'Unit',pos:['st','am','cm'],name:'Combination play to finish',focus:'One-twos, third-man runs, finishing',players:'3 attackers + GK',area:'Edge of the box',time:'15 min',int:'Medium',kit:'Balls ×12, 3 mannequins',
 setup:'Mannequins form a defensive line on the edge of the box. Striker in front of them, 10 and 8 behind.',
 steps:['The 8 plays into the striker’s feet','The striker lays it off to the 10','The 8 runs beyond the mannequins','The 10 plays the through ball to the 8','The 8 finishes first time'],
 pts:['Weight of pass: firm into feet, soft for lay-offs','Run as the ball travels, not after','Finish across the keeper'],
 prog:['Change the pattern every round','Add a live defender','Two-touch limit for everyone'],
 tm:{work:30,rest:30,rounds:8,sets:2,sr:90},
 sc:{view:'att',e:{a:[38,44,'8'],b:[50,30,'9'],c:[60,42,'10'],p1:[40,24,'','p'],p2:[50,24,'','p'],p3:[60,24,'','p'],g:[50,2,'GK','o']},b:'a',f:[
  {h:'Into feet',c:'The 8 plays into the striker.',b:'b',m:{b:[50,32]}},
  {h:'Lay-off',c:'Striker lays it off to the 10. The 8 starts his run.',b:'c',m:{a:[42,28]}},
  {h:'Through',c:'The 10 slips it through between the mannequins.',b:'a',m:{a:[45,14]}},
  {h:'Finish',c:'First-time finish.',b:[52,0],m:{g:[48,3]}}]}},

{id:'pos-game',cat:'Team',pos:['dm','cm','am'],name:'Positional game 4v4+3',focus:'Keeping the ball, finding the free player, scanning',players:'11 (4v4 + 3 neutrals)',area:'35 × 30 m',time:'20 min',int:'High',kit:'Balls ×8, bibs ×3 colours, cones',
 setup:'Two teams of four in a box with three neutral players (one at each end, one inside) who play for the team with the ball.',
 steps:['The team in possession keeps the ball with the neutrals’ help (7v4)','Score a point for 8 passes or for an end-to-end pass between the two end neutrals','On a turnover, the other team becomes the attacking side','Neutrals are limited to two touches','Play 4 × 4 min with 2 min rest'],
 pts:['Create width and depth: use the whole box','Find the player between the defenders','Counter-press immediately when you lose it','Scan before every touch'],
 prog:['Make the box smaller','Neutral players one-touch','Score in mini goals after reaching 6 passes'],
 tm:{work:240,rest:120,rounds:4,sets:1},
 sc:{view:'mid',grid:[[18,30,64,40,'35 × 30 m']],e:{a:[24,40,'A'],b:[46,36,'A'],c:[76,40,'A'],d:[50,60,'A'],n1:[50,30,'N','k'],n2:[50,70,'N','k'],n3:[50,50,'N','k'],x:[36,46,'B','o'],y:[58,44,'B','o'],z:[64,56,'B','o'],w:[40,58,'B','o']},b:'n2',f:[
  {h:'Start',c:'Bottom neutral has it. Team A spreads to make the box big.',b:'d'},
  {h:'Through',c:'Into the inside neutral between the lines.',b:'n3',m:{x:[42,50],y:[54,48]}},
  {h:'Width',c:'Out to the wide player, who has time.',b:'c',m:{z:[70,48]}},
  {h:'End to end',c:'Pass to the top neutral: point scored.',b:'n1'}]}},

{id:'build-press',cat:'Team',pos:['gk','cb','fb','dm'],name:'Build-up vs high press 7v5',focus:'Team structure in the first phase',players:'GK + 4 defenders + 2 midfielders v 5 pressers',area:'Defensive half',time:'20 min',int:'High',kit:'Balls ×10, 3 cone gates at halfway',
 setup:'Your keeper, back four and two midfielders play out against five pressers. Score by dribbling or passing through a gate at halfway.',
 steps:['Keeper starts every rep','Build-up shape: centre-backs split, full-backs high, 6 and 8 staggered','Pressers win a point by winning it and shooting within 6 s','Rotate the press start position each round','Coach stops play to show the free player'],
 pts:['Stagger the midfielders so they are not on the same line','Pass to the free man, not the nearest man','Use the keeper as an extra player','Switch play when one side is crowded'],
 prog:['Pressers +1 (7v6)','Two-touch limit for defenders','Gates only count after a switch of play'],
 tm:{work:240,rest:120,rounds:4,sets:1},
 sc:{view:'def',e:{g:[50,96,'GK'],a:[14,72,'LB'],b:[36,84,'LCB'],c:[64,84,'RCB'],d:[86,72,'RB'],e:[48,70,'6'],f:[62,58,'8'],x1:[40,80,'P','o'],x2:[60,80,'P','o'],x3:[22,70,'P','o'],x4:[78,70,'P','o'],x5:[52,64,'P','o'],c1:[30,50,'','c'],c2:[50,50,'','c'],c3:[70,50,'','c']},b:'g',f:[
  {h:'Shape',c:'Keeper has it. Centre-backs split, full-backs high, midfielders staggered.'},
  {h:'Bait',c:'Keeper plays to the left centre-back; the press shifts to that side.',b:'b',m:{x1:[34,82],x3:[16,70],x5:[44,68]}},
  {h:'Free man',c:'He finds the 8 between the lines on the far side.',b:'f',m:{f:[64,60]}},
  {h:'Through',c:'Drive through the gate. The press is beaten.',m:{f:[70,48]}}]}},

{id:'transition',cat:'Team',pos:['dm','cm','w','st'],name:'Win it, counter in 6 seconds',focus:'Transition to attack and counter-press',players:'6v6 + 2 GKs',area:'40 × 30 m',time:'20 min',int:'High',kit:'Balls ×10, 2 full goals or large mini goals, bibs',
 setup:'Small-sided game with goals. A goal scored within 6 seconds of winning the ball counts triple.',
 steps:['Teams play a normal small-sided game','Coach counts out loud when the ball is won','Goal within 6 s of a regain = 3 points','The team that loses the ball must counter-press immediately','4 × 4 min with 2 min rest'],
 pts:['First look forward after winning it','Run forward, not toward the ball','Nearest player to the loss hunts it','Others block passing lanes forward'],
 prog:['5 s window','Goals from regains in the attacking half count double','Add neutral wide players'],
 tm:{work:240,rest:120,rounds:4,sets:1},
 sc:{view:'mid',grid:[[14,22,72,56,'40 × 30 m']],e:{a:[40,52,'A'],b:[60,48,'A'],c:[30,36,'A'],d:[70,34,'A'],x:[50,50,'B','o'],y:[40,40,'B','o'],z:[62,62,'B','o'],gk:[50,24,'GK','o']},b:'x',f:[
  {h:'Regain',c:'Team A wins the ball in the middle.',b:'a',m:{a:[46,50]}},
  {h:'Forward',c:'First look forward: runners go beyond.',b:'b',m:{c:[36,30],d:[64,28],b:[58,44]}},
  {h:'Finish',c:'Through ball and finish inside 6 seconds: triple points.',b:'d',m:{d:[58,28]}},
  {h:'Score',c:'Goal.',b:[52,22]}]}},

{id:'block',cat:'Team',pos:['cb','fb','dm','cm','w'],name:'Compact block 8v6',focus:'Defending in two banks, sliding as a unit',players:'8 defenders v 6 attackers + GK',area:'Defensive third + midfield',time:'20 min',int:'Medium',kit:'Balls ×8, bibs, cones for 3 counter gates',
 setup:'Back four and midfield four defend the box against six attackers circulating the ball. Defenders score by winning it and passing through a gate at halfway.',
 steps:['Attackers circulate the ball around the block','Both lines slide together toward the ball side','Nearest player presses; those behind cover','Keep less than 12 m between the lines','Win the ball and counter through a gate'],
 pts:['Move with the ball while it travels','Stay compact horizontally and vertically','Show play wide, protect the middle','Communicate shifts every pass'],
 prog:['Attackers +1','Attackers can switch to a target player','Defenders must win it within 30 s'],
 tm:{work:240,rest:120,rounds:4,sets:1},
 sc:{view:'def',e:{d1:[18,80,'LB'],d2:[38,84,'CB'],d3:[62,84,'CB'],d4:[82,80,'RB'],m1:[18,68,'LM'],m2:[40,70,'CM'],m3:[60,70,'CM'],m4:[82,68,'RM'],x1:[14,56,'A','o'],x2:[38,54,'A','o'],x3:[62,54,'A','o'],x4:[86,56,'A','o']},b:'x2',f:[
  {h:'Central',c:'Ball central. Both banks narrow and compact.'},
  {h:'Slide',c:'Ball goes wide right. Everything slides together; right midfielder presses.',b:'x4',m:{m4:[84,60],m3:[68,68],m2:[52,70],m1:[34,70],d4:[82,76],d3:[66,82],d2:[50,84],d1:[32,82]}},
  {h:'Switch',c:'Switch to the left. Slide back across as the ball travels.',b:'x1',m:{m1:[18,60],m2:[32,68],m3:[48,70],m4:[66,70],d1:[18,74],d2:[34,82],d3:[50,84],d4:[66,82]},d:1700},
  {h:'Win',c:'Left midfielder presses and wins it. Counter.',b:'m1',m:{m1:[16,58]}}]}},

{id:'crossing',cat:'Team',pos:['fb','wb','w','st','cm'],name:'High-intensity crossing circuit',focus:'Crossing, box runs, conditioning',players:'8–12 + GK',area:'Half pitch',time:'20 min',int:'High',kit:'Balls ×15, 6 cones',
 setup:'Wide players in queues on both flanks at halfway. Two strikers and a late runner start 30 m from goal.',
 steps:['Midfielder plays a diagonal to the wide player','The wide player drives down the line and crosses','Striker 1 attacks the near post, striker 2 the far post','The late runner arrives at the cut-back zone','Everyone jogs back to the opposite queue'],
 pts:['Cross before the box gets crowded','Runners: one movement away, then attack','Late runner holds his run','Work at match speed'],
 prog:['Add 2 defenders, then 3','Alternate flanks every rep without a break','Only first-time finishes count'],
 tm:{work:30,rest:30,rounds:10,sets:2,sr:120},
 sc:{view:'att',e:{a:[86,50,'W'],b:[46,30,'9'],c:[58,32,'9'],d:[50,44,'8'],k:[40,56,'M'],g:[50,2,'GK','o'],c1:[20,30,'','c'],c2:[80,30,'','c']},b:'k',f:[
  {h:'Diagonal',c:'Midfielder plays the diagonal to the wide player.',b:'a',m:{a:[88,40]}},
  {h:'Drive',c:'Drive to the byline. Runners make one movement away first.',m:{a:[90,14],b:[40,20],c:[62,22],d:[50,34]}},
  {h:'Cross',c:'Cross. Near post, far post, and the late runner at the cut-back zone.',b:'b',m:{b:[46,8],c:[58,10],d:[52,22]}},
  {h:'Finish',c:'Finish, then jog to the other queue.',b:[48,0]}]}},

{id:'ssg-4v4',cat:'Team',pos:['gk','cb','fb','wb','dm','cm','am','w','st'],name:'Small-sided 4v4 conditioning',focus:'Fitness through game play, 1v1 duels',players:'8 (4v4)',area:'30 × 25 m',time:'24 min',int:'High',kit:'4 mini goals, balls ×10, bibs',
 setup:'4v4 with two mini goals at each end. Balls around the pitch for quick restarts.',
 steps:['Normal game, no offside','Coach restarts immediately when the ball goes out','Each team defends two goals and attacks two','4 min on, 2 min active recovery','4–5 rounds'],
 pts:['Keep the intensity high: this is your conditioning','Switch play to the less-defended goal','Press as a group of four'],
 prog:['Three-touch maximum','Goal only counts if all four players are in the attacking half','Reduce rest to 90 s'],
 tm:{work:240,rest:120,rounds:5,sets:1},
 sc:{view:'mid',grid:[[24,30,52,40,'30 × 25 m']],e:{g1:[36,30,'','g'],g2:[64,30,'','g'],g3:[36,70,'','g'],g4:[64,70,'','g'],a:[34,58,'A'],b:[50,62,'A'],c:[66,56,'A'],d:[50,46,'A'],x:[40,44,'B','o'],y:[60,44,'B','o'],z:[50,54,'B','o'],w:[56,36,'B','o']},b:'b',f:[
  {h:'Build',c:'Team A attacks the top two goals.',b:'a',m:{x:[38,50]}},
  {h:'Switch',c:'Switch to the less-defended side.',b:'c',m:{z:[58,54],y:[62,48]}},
  {h:'Score',c:'Drive and finish in the top-right goal.',m:{c:[64,38]},b:[64,30]}]}},

{id:'corners',cat:'Team',pos:['gk','cb','fb','dm','cm'],name:'Defending corners: zonal + man',focus:'Set-piece organisation',players:'10 defenders v 6–8 attackers',area:'Penalty area',time:'15 min',int:'Low',kit:'Balls ×12',
 setup:'Three players zonal along the six-yard line, two on the posts or edge, the rest man-marking the main threats.',
 steps:['Walk through positions without a ball','Coach delivers corners from both sides','Zonal players attack the ball in their zone','Man-markers stay goal-side and block runs','After the clearance, the whole team steps out together'],
 pts:['Zonal players: start still, attack forward, never backward','Markers: contact early, eyes on man and ball','Keeper commands the six-yard box','Clear high, wide and far'],
 prog:['Short corner variations','Second-ball clearance and counter','Attackers run blocking routines'],
 tm:{work:60,rest:60,rounds:8,sets:1},
 sc:{view:'def',e:{g:[50,98,'GK'],z1:[42,94,'Z'],z2:[50,94,'Z'],z3:[58,94,'Z'],e1:[50,82,'E'],m1:[44,88,'M'],m2:[56,88,'M'],x1:[42,86,'A','o'],x2:[56,86,'A','o'],x3:[50,80,'A','o'],k:[100,100,'C','o']},b:'k',f:[
  {h:'Set',c:'Three zonal at the six-yard line, two markers, one on the edge.'},
  {h:'Runs',c:'Attackers run. Markers stay goal-side; zonal players hold.',m:{x1:[48,90],x2:[60,92],x3:[52,86],m1:[48,91],m2:[60,94]}},
  {h:'Attack',c:'Ball delivered into zone two. Zonal player attacks it forward.',b:[50,92],m:{z2:[50,92]},d:1500},
  {h:'Clear',c:'Header clear. Everyone steps out together.',b:[30,64],m:{z1:[42,88],z2:[50,88],z3:[58,88],m1:[46,84],m2:[58,84]}}]}}
];
